apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name}}
  description: ${{values.description}}
  annotations:
    github.com/project-slug: ${{values.destination.owner}}/${{values.destination.repo}}
  tags:
    - python
    - fastapi
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner}}

