apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{values.name}}
  namespace: ${{values.namespace}}
  labels:
    app: ${{values.name}}
    version: v1
spec:
  replicas: ${{values.replicas}}
  selector:
    matchLabels:
      app: ${{values.name}}
  template:
    metadata:
      labels:
        app: ${{values.name}}
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "${{values.port}}"
        prometheus.io/path: "/metrics"
    spec:
      imagePullSecrets:
      - name: ghcr-credentials
      containers:
      - name: ${{values.name}}
        image: ghcr.io/${{values.destination.owner}}/${{values.name}}:latest
        imagePullPolicy: Always
        ports:
        - containerPort: ${{values.port}}
          name: http
          protocol: TCP
        env:
        - name: PORT
          value: "${{values.port}}"
        - name: SERVICE_NAME
          value: "${{values.name}}"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"

