apiVersion: v1
kind: Service
metadata:
  name: ${{values.name}}
  namespace: ${{values.namespace}}
  labels:
    app: ${{values.name}}
    backstage.io/kubernetes-id: ${{values.name}}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: ${{values.name}}

